### ISSUE TITLE
安装依赖报错

### ISSUE THREAD

**Issue by 13058004410** [cteamx/Thief#128]
在跟目录下运行npm i   结果报了很多错。

npm ERR! code 1
npm ERR! path C:\Users\f1305\Desktop\test\Thief\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe C:\Users\f1305\Desktop\test\Thief\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'C:\\Users\\f1305\\Desktop\\test\\Thief\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@18.12.1 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\f1305\Desktop\test\Thief\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\f1305\Desktop\test\Thief\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\f1305\Desktop\test\Thief\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\f1305\Desktop\test\Thief\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\f1305\Desktop\test\Thief\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\f1305\Desktop\test\Thief\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:207:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\f1305\Desktop\test\Thief\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\f1305\Desktop\test\Thief\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\f1305\Desktop\test\Thief\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\f1305\Desktop\test\Thief\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\f1305\Desktop\test\Thief\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\f1305\Desktop\test\Thief\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:207:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\f1305\Desktop\test\Thief\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\f1305\Desktop\test\Thief\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\f1305\Desktop\test\Thief\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\f1305\Desktop\test\Thief\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\f1305\Desktop\test\Thief\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\f1305\Desktop\test\Thief\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:207:21)
npm ERR! gyp verb `which` failed  python Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\f1305\Desktop\test\Thief\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\f1305\Desktop\test\Thief\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\f1305\Desktop\test\Thief\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\f1305\Desktop\test\Thief\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\f1305\Desktop\test\Thief\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\f1305\Desktop\test\Thief\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:207:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb could not find "python". checking python launcher
npm ERR! gyp verb could not find "python". guessing location
npm ERR! gyp verb ensuring that file exists: C:\Python27\python.exe
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
npm ERR! gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\f1305\Desktop\test\Thief\node_modules\node-gyp\lib\configure.js:484:19)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\f1305\Desktop\test\Thief\node_modules\node-gyp\lib\configure.js:509:16)
npm ERR! gyp ERR! stack     at callback (C:\Users\f1305\Desktop\test\Thief\node_modules\graceful-fs\polyfills.js:306:20)
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:207:21)
npm ERR! gyp ERR! System Windows_NT 10.0.22621
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\f1305\\Desktop\\test\\Thief\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd C:\Users\f1305\Desktop\test\Thief\node_modules\node-sass
npm ERR! gyp ERR! node -v v18.12.1
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\f1305\AppData\Local\npm-cache\_logs\2023-01-24T12_23_22_956Z-debug-0.log

**Comment by indomitableXiaoNan** [comment]
将nodejs版本降到10.24

**Comment by indomitableXiaoNan** [comment]
将nodejs版本降到10.24
将webpage.json里面所有依赖指定版本，并且
修改下面几个依赖的版本号（国内镜像有的版本已经没有了）
"electron": "8.5.5"
"vue": "2.5.17"
"vue-template-compiler": "2.5.17"
执行 npm install
在项目根目录下创建.npmrc文件添加
ELECTRON_MIRROR=https://registry.npmmirror.com/-/binary/electron/
ELECTRON_BUILDER_BINARIES_MIRROR=https://registry.npmmirror.com/-/binary/electron-builder-binaries/
执行npm run build
如果往后目前的版本也没了，就要改依赖源挂梯子下载，或者更改别的版本号，但是过高的版本会导致显示错误，可能要改代码
