### ISSUE TITLE
修改老板键闪退后重新打开失败

### ISSUE THREAD

**Issue by RexHuang1** [cteamx/Thief#25]
**版本：thief-book-3.1.0-win64.exe**
**问题描述：修改老板键为“ALT + 、”闪退后重新打开失败。**
**报错信息：**
`[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: Cannot find module '../tray'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (C:\Users\RexHuang\AppData\Local\Programs\thief-book\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.get [as Tray] (C:\Users\RexHuang\AppData\Local\Programs\thief-book\resources\electron.asar\browser\api\exports\electron.js:11:16)
    at v (C:\Users\RexHuang\AppData\Local\Programs\thief-book\resources\app.asar\dist\electron\main.js:1:36954)
    at App.<anonymous> (C:\Users\RexHuang\AppData\Local\Programs\thief-book\resources\app.asar\dist\electron\main.js:1:43578)
    at emitTwo (events.js:131:20)
    at App.emit (events.js:214:7)

[确定]`

[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
TypeError: Cannot read property 'setTitle' of undefined
    at p (C:\Users\RexHuang\AppData\Local\Programs\thief-book\resources\app.asar\dist\electron\main.js:1:33063)
    at Timeout._onTimeout (C:\Users\RexHuang\AppData\Local\Programs\thief-book\resources\app.asar\dist\electron\main.js:1:43561)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)

[确定]

**Comment by sanjinhub** [comment]
快捷键设置错误
